// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'
export const UPDATE_CURRENT_LAT = 'UPDATE_CURRENT_LAT'
export const UPDATE_CURRENT_LNG = 'UPDATE_CURRENT_LNG'
export const CURRENT_TAG = 'CURRENT_TAG'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'


//AppointementActions
export const UPDATE_PAYMENT_MODE = 'UPDATE_PAYMENT_MODE'

//Order
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_PHARM_ID = 'UPDATE_PHARM_ID'
export const RESET = 'RESET'
export const UPDATE_SUBTOTAL = 'UPDATE_SUBTOTAL' 
export const UPDATE_PROMO = 'UPDATE_PROMO' 
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const TAX_LIST = 'TAX_LIST'
export const UPDATE_DELIVERY_CHARGE = 'UPDATE_DELIVERY_CHARGE' 
{/*
export const UPDATE_PROMO = 'UPDATE_PROMO' 
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT' 
export const UPDATE_TOTAL = 'UPDATE_TOTAL'


export const UPDATE_TAX = 'UPDATE_TAX'
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_PHARMACIES = 'UPDATE_PHARMACIES'
export const UPDATE_PAYMENT_MODE = 'UPDATE_PAYMENT_MODE'
*/}

//Lab Order
export const UPDATE_LAB_ID = 'UPDATE_LAB_ID'
export const UPDATE_CURRENT_LAB_ID = 'UPDATE_CURRENT_LAB_ID'
export const UPDATE_LAB_ADD_TO_CART = 'UPDATE_LAB_ADD_TO_CART'
export const UPDATE_LAB_SUBTOTAL = 'UPDATE_LAB_SUBTOTAL' 
export const UPDATE_LAB_PROMO = 'UPDATE_LAB_PROMO' 
export const UPDATE_LAB_CALCULATE_TOTAL = 'UPDATE_LAB_CALCULATE_TOTAL'
export const UPDATE_LAB_DISCOUNT = 'UPDATE_LAB_DISCOUNT' 
export const UPDATE_LAB_TOTAL = 'UPDATE_LAB_TOTAL'
export const UPDATE_LAB_TAX_LIST = 'UPDATE_LAB_TAX_LIST'
export const UPDATE_LAB_TAX = 'UPDATE_LAB_TAX'
export const LAB_RESET = 'LAB_RESET'
export const UPDATE_LAB_PATIENT_NAME = 'UPDATE_LAB_PATIENT_NAME'
export const UPDATE_LAB_PATIENT_DOB = 'UPDATE_LAB_PATIENT_DOB'
export const UPDATE_LAB_PATIENT_GENDER_ID = 'UPDATE_LAB_PATIENT_GENDER_ID'
export const UPDATE_LAB_PATIENT_GENDER_NAME = 'UPDATE_LAB_PATIENT_GENDER_NAME'
export const UPDATE_LAB_PATIENt_PAYMENT_MODE = 'UPDATE_LAB_PATIENt_PAYMENT_MODE'
export const UPDATE_LABS = 'UPDATE_LABS'

//Prescription Order
export const UPDATE_PRESCRIPTION_ID = 'UPDATE_PRESCRIPTION_ID'
export const UPDATE_PRESCRIPTION_DETAILS = 'UPDATE_PRESCRIPTION_DETAILS'

//Paypal Status
export const PAYPAL_PAYMENT_STATUS = 'PAYPAL_PAYMENT_STATUS'

// Lab Reports
export const LOAD_LAB_REPORTS_START = 'LOAD_LAB_REPORTS_START'
export const LOAD_LAB_REPORTS_SUCCESS = 'LOAD_LAB_REPORTS_SUCCESS'
export const LOAD_LAB_REPORTS_ERROR = 'LOAD_LAB_REPORTS_ERROR'

// Orders
export const LOAD_COMPLETED_ORDERS_START = 'LOAD_COMPLETED_ORDERS_START'
export const LOAD_COMPLETED_ORDERS_SUCCESS = 'LOAD_COMPLETED_ORDERS_SUCCESS'
export const LOAD_COMPLETED_ORDERS_ERROR = 'LOAD_COMPLETED_ORDERS_ERROR'

export const LOAD_PENDING_ORDERS_START = 'LOAD_PENDING_ORDERS_START'
export const LOAD_PENDING_ORDERS_SUCCESS = 'LOAD_PENDING_ORDERS_SUCCESS'
export const LOAD_PENDING_ORDERS_ERROR = 'LOAD_PENDING_ORDERS_ERROR'

export const LOAD_ORDER_STATUS_START = 'LOAD_ORDER_STATUS_START'
export const LOAD_ORDER_STATUS_SUCCESS = 'LOAD_ORDER_STATUS_SUCCESS'
export const LOAD_ORDER_STATUS_ERROR = 'LOAD_ORDER_STATUS_ERROR'

// Customer Auth
export const CUSTOMER_LOGIN_START = 'CUSTOMER_LOGIN_START'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_ERROR = 'CUSTOMER_LOGIN_ERROR'

export const CUSTOMER_REGISTER_START = 'CUSTOMER_REGISTER_START'
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_ERROR = 'CUSTOMER_REGISTER_ERROR'

export const CHECK_PHONE_START = 'CHECK_PHONE_START'
export const CHECK_PHONE_SUCCESS = 'CHECK_PHONE_SUCCESS'
export const CHECK_PHONE_ERROR = 'CHECK_PHONE_ERROR'

// Cart
export const LOAD_CART_START = 'LOAD_CART_START'
export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS'
export const LOAD_CART_ERROR = 'LOAD_CART_ERROR'

// Home
export const LOAD_HOME_DETAILS_START = 'LOAD_HOME_DETAILS_START'
export const LOAD_HOME_DETAILS_SUCCESS = 'LOAD_HOME_DETAILS_SUCCESS'
export const LOAD_HOME_DETAILS_ERROR = 'LOAD_HOME_DETAILS_ERROR'

// Notifications
export const LOAD_NOTIFICATIONS_START = 'LOAD_NOTIFICATIONS_START'
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS'
export const LOAD_NOTIFICATIONS_ERROR = 'LOAD_NOTIFICATIONS_ERROR'

// Lab Cart Items
export const LOAD_LAB_CART_ITEMS_START = 'LOAD_LAB_CART_ITEMS_START'
export const LOAD_LAB_CART_ITEMS_SUCCESS = 'LOAD_LAB_CART_ITEMS_SUCCESS'
export const LOAD_LAB_CART_ITEMS_ERROR = 'LOAD_LAB_CART_ITEMS_ERROR'

// Patients
export const LOAD_PATIENTS_START = 'LOAD_PATIENTS_START'
export const LOAD_PATIENTS_SUCCESS = 'LOAD_PATIENTS_SUCCESS'
export const LOAD_PATIENTS_ERROR = 'LOAD_PATIENTS_ERROR'

export const DELETE_PATIENT_START = 'DELETE_PATIENT_START'
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS'
export const DELETE_PATIENT_ERROR = 'DELETE_PATIENT_ERROR'

// Last Address
export const LOAD_LAST_ADDRESS_START = 'LOAD_LAST_ADDRESS_START'
export const LOAD_LAST_ADDRESS_SUCCESS = 'LOAD_LAST_ADDRESS_SUCCESS'
export const LOAD_LAST_ADDRESS_ERROR = 'LOAD_LAST_ADDRESS_ERROR'

// Labs List
export const LOAD_LABS_LIST_START = 'LOAD_LABS_LIST_START'
export const LOAD_LABS_LIST_SUCCESS = 'LOAD_LABS_LIST_SUCCESS'
export const LOAD_LABS_LIST_ERROR = 'LOAD_LABS_LIST_ERROR'

// Add Patient
export const ADD_PATIENT_START = 'ADD_PATIENT_START'
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS'
export const ADD_PATIENT_ERROR = 'ADD_PATIENT_ERROR'

// Edit Patient
export const EDIT_PATIENT_START = 'EDIT_PATIENT_START'
export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS'
export const EDIT_PATIENT_ERROR = 'EDIT_PATIENT_ERROR'

// Place Lab Order
export const PLACE_LAB_ORDER_START = 'PLACE_LAB_ORDER_START'
export const PLACE_LAB_ORDER_SUCCESS = 'PLACE_LAB_ORDER_SUCCESS'
export const PLACE_LAB_ORDER_ERROR = 'PLACE_LAB_ORDER_ERROR'

// Tax List
export const LOAD_TAX_LIST_START = 'LOAD_TAX_LIST_START'
export const LOAD_TAX_LIST_SUCCESS = 'LOAD_TAX_LIST_SUCCESS'
export const LOAD_TAX_LIST_ERROR = 'LOAD_TAX_LIST_ERROR'

// Customer Profile
export const LOAD_CUSTOMER_PROFILE_START = 'LOAD_CUSTOMER_PROFILE_START'
export const LOAD_CUSTOMER_PROFILE_SUCCESS = 'LOAD_CUSTOMER_PROFILE_SUCCESS'
export const LOAD_CUSTOMER_PROFILE_ERROR = 'LOAD_CUSTOMER_PROFILE_ERROR'

export const UPDATE_CUSTOMER_PROFILE_START = 'UPDATE_CUSTOMER_PROFILE_START'
export const UPDATE_CUSTOMER_PROFILE_SUCCESS = 'UPDATE_CUSTOMER_PROFILE_SUCCESS'
export const UPDATE_CUSTOMER_PROFILE_ERROR = 'UPDATE_CUSTOMER_PROFILE_ERROR'

export const UPLOAD_PROFILE_PICTURE_START = 'UPLOAD_PROFILE_PICTURE_START'
export const UPLOAD_PROFILE_PICTURE_SUCCESS = 'UPLOAD_PROFILE_PICTURE_SUCCESS'
export const UPLOAD_PROFILE_PICTURE_ERROR = 'UPLOAD_PROFILE_PICTURE_ERROR'

export const UPDATE_PROFILE_PICTURE_START = 'UPDATE_PROFILE_PICTURE_START'
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS'
export const UPDATE_PROFILE_PICTURE_ERROR = 'UPDATE_PROFILE_PICTURE_ERROR'

// Delete Cart Item
export const DELETE_CART_ITEM_START = 'DELETE_CART_ITEM_START'
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS'
export const DELETE_CART_ITEM_ERROR = 'DELETE_CART_ITEM_ERROR'

// Apply Coupon
export const APPLY_COUPON_START = 'APPLY_COUPON_START'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_ERROR = 'APPLY_COUPON_ERROR'

// Relevance Data
export const LOAD_RELEVANCE_DATA_START = 'LOAD_RELEVANCE_DATA_START'
export const LOAD_RELEVANCE_DATA_SUCCESS = 'LOAD_RELEVANCE_DATA_SUCCESS'
export const LOAD_RELEVANCE_DATA_ERROR = 'LOAD_RELEVANCE_DATA_ERROR'

// Add To Cart Item
export const ADD_TO_CART_ITEM_START = 'ADD_TO_CART_ITEM_START'
export const ADD_TO_CART_ITEM_SUCCESS = 'ADD_TO_CART_ITEM_SUCCESS'
export const ADD_TO_CART_ITEM_ERROR = 'ADD_TO_CART_ITEM_ERROR'

// Lab Details
export const LOAD_LAB_DETAILS_START = 'LOAD_LAB_DETAILS_START'
export const LOAD_LAB_DETAILS_SUCCESS = 'LOAD_LAB_DETAILS_SUCCESS'
export const LOAD_LAB_DETAILS_ERROR = 'LOAD_LAB_DETAILS_ERROR'

// Profiles
export const LOAD_PROFILES_START = 'LOAD_PROFILES_START'
export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS'
export const LOAD_PROFILES_ERROR = 'LOAD_PROFILES_ERROR'

// Packages
export const LOAD_PACKAGES_START = 'LOAD_PACKAGES_START'
export const LOAD_PACKAGES_SUCCESS = 'LOAD_PACKAGES_SUCCESS'
export const LOAD_PACKAGES_ERROR = 'LOAD_PACKAGES_ERROR'

// Tests
export const LOAD_TESTS_START = 'LOAD_TESTS_START'
export const LOAD_TESTS_SUCCESS = 'LOAD_TESTS_SUCCESS'
export const LOAD_TESTS_ERROR = 'LOAD_TESTS_ERROR'

// All Addresses
export const LOAD_ALL_ADDRESSES_START = 'LOAD_ALL_ADDRESSES_START'
export const LOAD_ALL_ADDRESSES_SUCCESS = 'LOAD_ALL_ADDRESSES_SUCCESS'
export const LOAD_ALL_ADDRESSES_ERROR = 'LOAD_ALL_ADDRESSES_ERROR'

export const SET_ACTIVE_ADDRESS_START = 'SET_ACTIVE_ADDRESS_START'
export const SET_ACTIVE_ADDRESS_SUCCESS = 'SET_ACTIVE_ADDRESS_SUCCESS'
export const SET_ACTIVE_ADDRESS_ERROR = 'SET_ACTIVE_ADDRESS_ERROR'

export const ADD_ADDRESS_START = 'ADD_ADDRESS_START'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR'

export const GET_LAST_ACTIVE_ADDRESS_START = 'GET_LAST_ACTIVE_ADDRESS_START'
export const GET_LAST_ACTIVE_ADDRESS_SUCCESS = 'GET_LAST_ACTIVE_ADDRESS_SUCCESS'
export const GET_LAST_ACTIVE_ADDRESS_ERROR = 'GET_LAST_ACTIVE_ADDRESS_ERROR'

// Lab Pending Orders
export const LOAD_LAB_PENDING_ORDERS_START = 'LOAD_LAB_PENDING_ORDERS_START'
export const LOAD_LAB_PENDING_ORDERS_SUCCESS = 'LOAD_LAB_PENDING_ORDERS_SUCCESS'
export const LOAD_LAB_PENDING_ORDERS_ERROR = 'LOAD_LAB_PENDING_ORDERS_ERROR'

// Lab Order Details
export const LOAD_LAB_ORDER_DETAILS_START = 'LOAD_LAB_ORDER_DETAILS_START'
export const LOAD_LAB_ORDER_DETAILS_SUCCESS = 'LOAD_LAB_ORDER_DETAILS_SUCCESS'
export const LOAD_LAB_ORDER_DETAILS_ERROR = 'LOAD_LAB_ORDER_DETAILS_ERROR'

// Upload Report
export const UPLOAD_REPORT_START = 'UPLOAD_REPORT_START'
export const UPLOAD_REPORT_SUCCESS = 'UPLOAD_REPORT_SUCCESS'
export const UPLOAD_REPORT_ERROR = 'UPLOAD_REPORT_ERROR'
export const UPLOAD_REPORT_RESET = 'UPLOAD_REPORT_RESET'
